services:
  riratodolist.api:
    image: ${DOCKER_REGISTRY-}riratodolistapi
    build:
      context: .
      dockerfile: RiraToDoList.API/Dockerfile
    container_name: RiraToDoList-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__SqlConnection=Server=sqlserver;Database=RiraToDoList;User=sa;Password=Iamirehsan1998!;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    restart: always

  # SQL Server Service
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1435:1433"
    environment:
      SA_PASSWORD: "Iamirehsan1998!"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Iamirehsan1998!", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    restart: always

volumes:
  sqlserver-data:
    driver: local
